Adds an options parameter to "loadStylesheet"
betsol/load-stylesheet pull request #1
Opened 2017-05-28 21:40 UTC by harm-less

Hey,

Guess what, I'm pretty much ready with a first release. A few minutes ago I published the repo and made sure most is working. I think everything is working out better than I expected as the hooks in UI Router 1.0 are awesome :D

The only things left are some failing units tests in TravisCI and a feature I build into this repo (hence the PR).

Please review it and let me know what you think from this PR and the new repo you can find here:
https://github.com/harm-less/angular-ui-router-css

Harm

2017-05-30 15:42 UTC, slavafomin commented
Hello Harm!

I've seen your demo and it works great, good job!

I will study it further and will response to this PR soon.

2017-05-30 15:57 UTC, slavafomin requested changes
The PR looks great, thanks! I've added some very trivial comment, please address it and I will happily merge.

2017-05-30 15:57 UTC, slavafomin commented on README.md
> +```insertBefore```: This should be another element which is part of your HTML's head
Why are you using three commas instead of just one?

2017-05-30 19:41 UTC, harm-less commented on README.md
> +```insertBefore```: This should be another element which is part of your HTML's head
It's the way I always used it, I didn't know one resulted in the same thing. It seems just one does the trick too when you don't have to specify the language. Thanks for pointing that out.

2017-05-30 19:43 UTC, harm-less commented
I fixed it, this meets your requirements, right?

2017-05-31 02:03 UTC, merged

2017-05-31 02:04 UTC, slavafomin commented
Great, thanks! Just merged it. Going to make a release soon.

2017-05-31 02:20 UTC, slavafomin commented
I've just released version `1.1.0`, feel free to check it out. And thanks again! Cheers ;)